<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Tomboy</RootNamespace>
    <AssemblyName>Tomboy</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GtkSharp" Version="3.24.24.95" />
    <PackageReference Include="Tmds.DBus" Version="0.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tomboy.Latex\Tomboy.Latex.csproj" />
  </ItemGroup>
</Project>
